lsst/ap_association

python/lsst/ap/association/assoc_db_sqlite.py, python/lsst/ap/association/association.py, python/lsst/ap/association/dia_collection.py, python/lsst/ap/association/dia_object.py, tests/test_association_db_sqlite.py, tests/test_association_task.py, tests/test_dia_collection.py, tests/test_dia_object.py
Previous the code returned the index in the the list of DIAObjects
in the DIACollection.
Fixed bugs in unittests.
=> DM-11921: Change match method in DIAObjectCollection to return DIAObject ids

python/lsst/ap/association/association.py, tests/test_association_db_sqlite.py, tests/test_association_task.py, tests/test_dia_collection.py
Moved the score and match methods from DIAObjectCollection into AssociationTask. Also fixed problems associated with SkyWcs.
=> DM-13477: Move association math from DIAObjectCollection into AssociationTask

doc/.gitignore, doc/ap_association/index.rst, doc/conf.py, doc/index.rst, doc/lsst.ap.association/index.rst, doc/manifest.yaml, python/lsst/ap/association/assoc_db_sqlite.py, python/lsst/ap/association/association.py, python/lsst/ap/association/dia_collection.py, python/lsst/ap/association/dia_object.py, tests/test_association_db_sqlite.py, tests/test_association_task.py, tests/test_dia_collection.py, tests/test_dia_object.py
Create numpydocs and enable sphinx.
=> DM-13916: Numpydoc conversion for ap_association.

COPYRIGHT, doc/lsst.ap.association/index.rst, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.FractionUpdatedDiaObjectsMetricTask.rst, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.NumberNewDiaObjectsMetricTask.rst, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.NumberUnassociatedDiaObjectsMetricTask.rst, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.TotalUnassociatedDiaObjectsMetricTask.rst, python/lsst/ap/association/metrics.py, tests/test_metrics.py, ups/ap_association.table
This PR defines `MetricTask` subclasses for the `ap_association.numNewDiaObjects`, `ap_association.numUnassociatedDiaObjects`, `ap_association.fracUpdatedDiaObjects`, and `ap_association.totalUnassociatedDiaObjects` metrics, which were previously implemented as functions in `ap_verify` (see lsst/ap_verify#63). This change requires that `ap_association` depend on `lsst.verify`.
Design note: most of the complexity of the task code comes from `MetricTask` instances not being allowed to assume a particular granularity for their metric. This, in turn, is partly because of Gen 2 (i.e., `MetricsControllerTask`) limitations, but largely because it's not yet known who will be responsible for metrics aggregation.
=> DM-16536: Migrate all metrics from ap.verify.measurements

python/lsst/ap/association/association.py
Doesn't fix the problem described in the ticket as it is more fundamental than what is going on in ap_association. However, the new code is a bit clearer and simpler so it's worth merging.
=> DM-20536: Can't count on `obj_idxs` being in bounds

python/lsst/ap/association/metrics.py, tests/test_metrics.py
This PR changes metadata-based metrics to take single inputs, following support for non-aggregating metrics in lsst/verify#54.
=> DM-20974: Remove aggregation support/requirement from MetricTask

tests/test_metrics.py
This PR removes tests of `adaptArgsAndRun` and `getInputDatasetTypes` from the metric test suite. These tests would have been broken by the Gen 3 migration, and testing their functionality is redundant because these methods should not be overloaded (following the changes in lsst/verify#55).
The PR also simplifies some of the code for testing `TestTotalUnassociatedObjects`, removing some special-casing. It must be merged together with lsst/verify#55, which makes supporting changes to the generic test code.
=> DM-21098: Isolate outdated Gen 3 methods in gen2tasks

python/lsst/ap/association/metrics.py, tests/test_metrics.py
This PR changes the behavior of `FractionUpdatedDiaObjectsMetricTask` when there are no pre-existing objects. This case is now treated as "not applicable" rather than as a computation failure in the metric.
=> DM-20902: FractionUpdatedDiaObjectsMetricTask should expect 0 DIAObjects

tests/test_metrics.py
The PR updates the unit tests for `TotalUnassociatedDiaObjectsMetricTask` to provide multiple inputs, as required following lsst/verify#57.
=> DM-21877: Create "marker" Butler dataset for PPDB

python/lsst/ap/association/__init__.py, python/lsst/ap/association/association.py, python/lsst/ap/association/diaCalculation.py, python/lsst/ap/association/diaCalculationPlugins.py, python/lsst/ap/association/diaForcedSource.py, python/lsst/ap/association/loadDiaCatalogs.py, tests/test_association_task.py, tests/test_diaForcedSource.py, tests/test_dia_calculation_plugins.py, tests/test_loadDiaCatalogs.py
Restructure ap_association to accomidate preloading.
Remove DiaObject/Source loading from association.
Change sphgeom HTM indexer.
Debug HTM diaCalc plugin.
Add mock Apdb to DiaForced unittest.
Change to sphgeom indexer.
Change update_dia_objects unittest.
Add htmIndex calculation to unittest.
Debug update diaObjects.
Edit association run method unittest.
Debug test_run.
Debug all association tests.
Create loadDiaCatalogs tests.
Add getPixelRanges test.
Add unittest for getPixelRanges
Debug getPixelRanges test.
Add object, source, and run tests.
debug loadDiaCatalogs unittests.
Add comment to diaCaluclation.
=> DM-22478: Lightly restructure ap_association tasks and create new DiaObject/DiaSource pre-loading task.

tests/test_metrics.py
This PR adds the `lsst.pipe.base.testUtils.assertValidOutput` assertion to existing tests of `MetricTask` classes.
=> DM-23426: Use PipelineTask test framework for MetricTask

python/lsst/ap/association/mapApData.py
This PR updates all calls to `yaml.load_all`, per the [Community post](https://community.lsst.org/t/3631) on the subject.
=> DM-23651: ap_pipe calls some deprecated things

python/lsst/ap/association/afwUtils.py, python/lsst/ap/association/mapApData.py, tests/test_association_task.py, tests/test_map_ap_data.py, tests/test_packageAlerts.py
This PR fixes a bug that caused `MapDiaSourceTask` to sometimes report observatory-specific filters, which would then get propagated to table columns. It updates all `ap_association` code to standardize filter names.
=> DM-25040: ap_association uses physical filter in Gen 3

python/lsst/ap/association/diaPipe.py, tests/test_diaPipe.py
This PR modifies `DiaPipelineTask`'s inputs to match `ImageDifferenceTask`'s outputs, as modified by lsst/pipe_tasks#390. The most substantial change is having it take its input "schema" as a catalog, as this is how schemas are persisted by the Butler.
=> DM-21939: Create Gen 3 AP Pipeline

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/packageAlerts.py, tests/test_diaPipe.py, tests/test_packageAlerts.py
Use within packageAlerts.
Debug unittests.
=> DM-24327: Include coadd cutouts in alert packets

python/lsst/ap/association/mapApData.py, tests/test_association_task.py, tests/test_packageAlerts.py
Explicitly use `getCanonicalFilter()[0]` as an interim solution.
=> DM-25746: filterName in APDB needs to be one of g, r, i, z, or y

python/lsst/ap/association/packageAlerts.py, tests/test_packageAlerts.py
In https://github.com/lsst/alert_packet/pull/21, we would like to change lsst.alert.packet's behavior to stream alerts out from disk rather than loading them entirely into memory, since alert files might be very large. Technically, this breaks no APIs, since the documented return value is an "iterable."
Making that change requires this one: change the test code so that it loads data into a list explicitly.
=> DM-25826: Explicitly cast alert data to a list in tests

python/lsst/ap/association/association.py
Pandas 1.1.0 now throws a KeyError in parts of the code. The fix is to use the `iat` accessor.
=> Use iat accessor for pandas 1.1.0 compatibility

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/metrics.py
This PR fixes a bug in `DiaPipelineTask` that got missed in review, and prevents `TotalUnassociatedDiaObjectsMetricTask` from calling an error when run at instrument granularity (it is still not clear whether tasks that access the APDB should be at repository or instrument granularity, but their current connections declare the latter).
Must be merged together with lsst/ap_pipe#57.
=> DM-21919: Run ap_verify end-to-end in Gen 3

python/lsst/ap/association/diaForcedSource.py, python/lsst/ap/association/mapApData.py, tests/test_association_task.py, tests/test_packageAlerts.py
As in DM-25746, this is a temporary workaround to enable R2 and I2 processing with ap_pipe. All the APDB filter name columns presently require a single character, and the DiaForcedSource table is no exception.
=> DM-25990: Reprocess HSC COSMOS medium dataset with ap_pipe

python/lsst/ap/association/diaPipe.py
This is a belated fix for an API change on DM-30649.
=> DM-30798: Update to new adjustQuantum signature.

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/transformDiaSourceCatalog.py
Using getPackageDir means that the path is burned into the config on read but this leads to the config stored in quantum graphs having a hard coded path to the location of ap_association at that time. For some workflow systems the path to the software on the execution node is in a different place so this breaks everything. This change embeds the environment variable in the config and relies on the runtime to call expandvars.
=> DM-30985: Use lazy evaluation of functor file and flag map

python/lsst/ap/association/diaForcedSource.py
Have to skip these columns until we update apdb on DM-31193.
=> DM-29346: Compute PSFlux chi squared metric

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/transformDiaSourceCatalog.py
This PR tweaks `TransformDiaSourceCatalogTask` so that `DiaPipelineTask` can be unit-tested in lsst/ap_pipe#86, and adds some missing documentation to `DiaPipelineTask`.
=> DM-31220: Use new DiaPipelineTask API in ApPipeTask

python/lsst/ap/association/diaForcedSource.py
so that it can be used there. It was renamed to
base_TransformedCentroidFromCoord to disambiguate from
base_TransformedCentroid
=> DM-31601: Move ap_assoc_TransformedCentroid  to meas_base

python/lsst/ap/association/transformDiaSourceCatalog.py
Corresponds to the removal of the default Ra/DecColumn
functors from from PostprocessAnalysis.
=> DM-28394: Remove workaround for hard-coded coord functors.

data/flag-rename-rules.yaml, python/lsst/ap/association/transformDiaSourceCatalog.py
-  Adapt to parent class optional primaryKey config.
-  Inherit config from base task
-  Add config parameter to switch whether flags are transformed as one bit-packed column named 'flags' or individual boolean columns  with column rename rules applied.
=> DM-31825: Implement RFC-807 on DRP parquet table consistency

python/lsst/ap/association/diaForcedSource.py, python/lsst/ap/association/packageAlerts.py, tests/test_packageAlerts.py
This PR removes uses of `VisitInfo.getExposureId()`, which was deprecated in lsst/afw#614.
=> DM-13943: Deprecate VisitInfo.getExposureId()

tests/test_diaPipe.py
With the task mocked out the metadata values calculated
by the task are no longer real values but are themselves
MagicMock objects. MagicMock objects can't be stored in
a TaskMetadata so we need to mock out the API that
sets the metadata.
This works with PropertySet since that seems to accept
the value and silently ignores it.
=> DM-32682: Mock out metadata setting in test

doc/conf.py
Update conf.py for the new documenteer 0.6 configuration API.  Based on
the latest updates in the package template
(https://github.com/lsst/templates/tree/master/project_templates/stack_package)
=> DM 30015: Update conf.py for documenteer 0.6

data/DiaSource.yaml
Adds `trailFlux` to `DiaSources.yaml`.
Note: Flux error is not implemented yet, so a place-holder is given to the functor. That argument is not used in the transformation anyways.
=> DM-34363: Add trailFlux measurement to ap_association

python/lsst/ap/association/diaPipe.py
This PR changes `DiaPipelineTask` to use `fakes_calexp` when appropriate, consistent with other input datasets.
=> DM-32694: Split AP pipeline into ApPipeWithFakes

python/lsst/ap/association/metrics.py, python/lsst/ap/association/skyBotEphemerisQuery.py
This PR fixes some copy-pasted docstrings, borrowing text from the code that calculated the metadata in the first place. It also documents the ephemeris catalog format so that we know what information we have for future development.
=> DM-33821: Update docstrings for solar system metrics.

python/lsst/ap/association/diaForcedSource.py, tests/test_diaForcedSource.py, tests/test_loadDiaCatalogs.py, tests/test_packageAlerts.py, tests/test_transformDiaSourceCatalog.py
This PR removes references to `getFilterLabel` and similarly-named methods, replacing them with `getFilter` (etc.) methods backed by `FilterLabel`.
=> DM-27177: Deprecate transitional getFilterLabel API

python/lsst/ap/association/transformDiaSourceCatalog.py
I'm restoring the use of `empty` here because that was an intentional choice (all the fields will get initialized in the loop), and it's good to have a note as to why that `int` really is necessary.
=> DM-35331: Add note about int requirement, and restore np.empty

COPYRIGHT, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.FractionUpdatedDiaObjectsMetricTask.rst, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.NumberNewDiaObjectsMetricTask.rst, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.NumberUnassociatedDiaObjectsMetricTask.rst, doc/lsst.ap.association/tasks/lsst.ap.association.metrics.TotalUnassociatedDiaObjectsMetricTask.rst, python/lsst/ap/association/metrics.py, tests/test_metrics.py
This PR removes use of the `lsst.verify.gen2tasks.register` decorator as well as all references to `lsst.verify.gen2tasks.MetricsControllerTask`. Both are removed in lsst/verify#103.
=> DM-33256: Remove Gen 2 support from verify

python/lsst/ap/association/metrics.py, tests/test_metrics.py
This PR removes all code for handling `None` inputs from concrete `MetricTasks` and raises `NoWorkFound` where appropriate.
=> DM-30869: Modernize MetricTask for better Gen 3 workflow

python/lsst/ap/association/diaPipe.py, tests/test_diaPipe.py
This PR removes references to `Dataset.append` that weren't covered by unit tests, and tweaks the tests so that they don't make assumptions about the call signatures in application code. It does not try to expand test coverage to perform actual Pandas operations, since I don't see a way to introduce mock tables without making them brittle to external changes.
=> DM-36058: Fix untested Pandas deprecation warnings in ap_association

python/lsst/ap/association/diaForcedSource.py, python/lsst/ap/association/packageAlerts.py
This makes them come from the code that called the run method with expIdBits.
=> DM-40032: Add stacklevel parameter to the warnings

python/lsst/ap/association/packageAlerts.py
This allows it to be read from anywhere supported by ResourcePath.
Requires lsst/alert_packet#35
=> DM-39938: Allow schema file to be a general URI

python/lsst/ap/association/__init__.py, python/lsst/ap/association/association.py, python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/metrics.py, python/lsst/ap/association/skyBotEphemerisQuery.py, python/lsst/ap/association/trailedSourceFilter.py, tests/test_association_task.py, tests/test_diaPipe.py, tests/test_trailedSourceFilter.py
Make trailedAssociatorTask which filters out trails whose lengths are above 0.416 arcseconds/second in length. The trailed sources are currently dropped once they are filtered out. More complexity for filtering will be added at a later date.
=> DM-38850: Make trailedAssociatorTask

data/association-flag-map.yaml, python/lsst/ap/association/association.py, python/lsst/ap/association/trailedSourceFilter.py, tests/test_association_task.py, tests/test_trailedSourceFilter.py
Now that trailed sources which cross over into edge regions are flagged, add in a filter to trailedSourceFilter.py. Currently, this filter is far more aggressive than it should be as it counts trailed sources crossing over into nodata regions as edges. This will be fixed in a later commit.
=> DM-40412: Add edge flag filtering to trailedSourceFilter.py

data/association-flag-map.yaml
This PR adds two flags to the flag map. One is so the new streak mask info makes it into `associatedDiaSources`. The other is for backwards compatibility with DM-40412.
=> DM-32769: Implement streak detection and masking in single frame processing

python/lsst/ap/association/metrics.py
I'm a little surprised the previous code ever worked with DataCoordinate objects - while they used to have keys(), it returned a set of Dimension instance, not strings.  I assume it did because Dimension.__eq__ accepts strings, but it isn't obvious that should translate into mixed-typed set differences working.
=> DM-34340: Adapt to daf_butler API changes.

data/association-flag-map.yaml
Added flagging of sources near the INJECTED and INJECTED_TEMPLATE  mask planes
=> DM-39466: Added flagging of sources near the INJECTED and INJECTED_TEMPLATE 

python/lsst/ap/association/__init__.py, python/lsst/ap/association/filterDiaSourceCatalog.py, python/lsst/ap/association/transformDiaSourceCatalog.py, tests/test_filterDiaSourceCatalog.py
Create a new pipelineTask that selects sources from the diaSource catalog and writes a goodSeeingDiff_candidateDiaSrc (or similar name) catalog that can be used as an input to TransiNetTask.
=> DM-40798: Exclude sky sources from RB classification

tests/test_loadDiaCatalogs.py, tests/test_packageAlerts.py
The `makeSchema` method is now a class method instead of instance method and it takes configuration object as a parameter.
=> DM-42489: Update tests for changes in Apdb.makeSchema interface

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/packageAlerts.py, tests/test_packageAlerts.py
Add a producer to packageAlerts in ap_association. The producer will send alerts from the pipeline to the alert stream using several environment variables to set the server, user, password, and topic.
Jenkins run here: https://rubin-ci.slac.stanford.edu/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/571/pipeline
=> DM-40414: Write PipelineTask to transmit alerts to Kafka

python/lsst/ap/association/diaPipe.py
Change default of `doWriteAssociatedSources` to True
=> DM-41108: Do write associated sources by default

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/loadDiaCatalogs.py
This is a debugging-only option. I elected to pass `doLoadForcedSources` in to `LoadDiaCatalogsTask.run()` rather than set it as a config of the subtask, thinking that it would be easier to remove in the future this way. I would welcome alternate suggestions!
=> DM-43389: Add option to disable loading diaForcedSource history

python/lsst/ap/association/packageAlerts.py, tests/test_packageAlerts.py
The new function `_check_server` pings the kafka server and checks if there are any available topics. If the server is not contactable or if the server topics are empty, it raises and error and stops the pipeline.
=> DM-43014: Reduce alert stream credentials timeout

python/lsst/ap/association/packageAlerts.py, tests/test_packageAlerts.py
As writing failed alerts to disk is only used for debugging, it should not be on by default and instead a configuration should be set when we want to inspect the alerts.
=> DM-43522:Remove too large alert packet write to disk

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/loadDiaCatalogs.py, tests/test_loadDiaCatalogs.py, tests/test_packageAlerts.py
APDB interface replaced the use of daf_base.DateTime with astropy Time, this patch updates client code to convert DateTtime to astropy Time when passing arguments to Apdb.
=> DM-43509: Switch to astropy.time in calls to Apdb methods

python/lsst/ap/association/packageAlerts.py
Add timeout config to packageAlerts and set the default to 15 seconds. The current static timeout appears to be too short, causing timeouts when the pipeline initializes and intermittently when alerts are being sent.
=> DM-43590: Add timeout config field

tests/test_loadDiaCatalogs.py, tests/test_packageAlerts.py
APDB initialization is now done via special class method `init_database`, test cases in this package are updated to use new API.
=> DM-43414: Update unit tests for changes in APDB API

tests/test_diaPipe.py, tests/test_loadDiaCatalogs.py, tests/test_packageAlerts.py
This PR cleans up handling of temporary files and directories in this package's unit tests. There are no references to `tempfile` in the library code itself.
=> DM-43618: ap_association tests leave apdb.sqlite3 files behind

doc/lsst.ap.association/index.rst, python/lsst/ap/association/diaPipe.py, tests/test_diaPipe.py, tests/test_metrics.py
This PR modifies `DiaPipelineTask` to use new-style configs instead of a nested `ApdbConfig` field, and updates the unit tests for `TestTotalUnassociatedObjects` to reflect lsst/verify#124. It also does some simplification of the task's unit tests.
=> DM-43416: Migrate AP code to external APDB configs

tests/test_diaPipe.py, tests/test_loadDiaCatalogs.py, tests/test_packageAlerts.py, tests/test_trailedSourceFilter.py, tests/test_transformDiaSourceCatalog.py, tests/utils_tests.py
Set up random generator seed in two places, main location is the `utils_tests.py` that is reused broadly.
=> DM-42744: Fix random seeds for `ap_association` unit tests

python/lsst/ap/association/filterDiaSourceCatalog.py
This PR removes a temporary `print` statement that was bypassing the logger.
=> DM-44279: Remove extra print statement from FilterDiaSourceCatalogTask

python/lsst/ap/association/packageAlerts.py, tests/test_packageAlerts.py
For some alerts, the footprint size allows the creation of cutouts which are far too large. This ticket adds a maxCutoutSize config to limit the maximum size. The maximum size will be the maximum trail length allowed for a 30 second exposure in pixels (62.5) plus the expected psf size (40 pixels). This comes to 102 pixels.
=> DM-41873: Add max cutout size to packageAlerts

data/DiaSource.yaml
Use new `ConvertDetectorAngleToPositionAngle` from `pipe_tasks` (in branch of same name) to write out dipoleAngle and trailAngle in position angle on sky (E of N in sky coordinates), instead of orientation (+y from +x in detector coordinates).
=> DM-44535: Express dipoleAngle, trailAngle in position angle on sky instead of detector angle

python/lsst/ap/association/utils.py, tests/test_utils.py
This PR fixes a bug in which `make_empty_catalog` did not create an empty catalog and did not convert the input schema to Pandas datatypes.
=> DM-44937: DiaForcedSource tables indexed by class, not integer

python/lsst/ap/association/packageAlerts.py
Add producer.close() to the alert producer to ensure that the producer closes safely.
=> DM-45023: Add close to producer

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/loadDiaCatalogs.py, python/lsst/ap/association/packageAlerts.py
This PR adds standard status logs to APDB loading, APDB storage, and alert packaging, all steps of `DiaPipelineTask` in which the code may fail to log for a minute or more. The lack of prior logging in PackageAlertsTask means it's hard to tell how much of the silence is from `apdb.store` and how much from packaging.
This PR also adds a loop logger (`utils.logging.PeriodicLogger`) to `PackageAlertsTask`. No such logging is practical for `Apdb` implementations, which treats the DB operations as bulk reads or writes rather than an explicit loop.
=> DM-43599: Add progress logs to DiaPipelineTask

python/lsst/ap/association/packageAlerts.py
Schema ids are now assigned based on the schema version
=> DM-42606: Add dynamic schema id assignment

python/lsst/ap/association/__init__.py, python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/mpSkyEphemerisQuery.py, python/lsst/ap/association/ssoAssociation.py, python/lsst/ap/association/utils.py, tests/test_diaPipe.py, tests/test_utils.py
Adding mpSkyEphemerisQuery, which replaces SkyBot in querying mpSky for ssObjects in the pre-load step.
=> DM-42576: mpSkyEphemerisQuery

python/lsst/ap/association/loadDiaCatalogs.py
This PR provides a more precise implementation of `LoadDiaCatalogsConfig.angleMargin` that fits more closely to the detector footprint. The implementation is *not* guaranteed to move all sides of the footprint outward by exactly `angleMargin`, but I assume such precision is not needed in a buffer.
=> DM-45789: Optimize region for LoadDiaCatalogs

python/lsst/ap/association/diaForcedSource.py, python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/packageAlerts.py, tests/test_packageAlerts.py
Also includes changes from DM-46058, but will be rebased
=> DM-46050: Add option to use image average PSF for alert cutouts.

python/lsst/ap/association/diaForcedSource.py, python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/packageAlerts.py
DiaObjects with too few detections are now skipped for running forced photometry. When packaging alerts, we must also skip packaging those forced sources.
=> DM-47081: Skip packaging missing forced sources

python/lsst/ap/association/diaPipe.py, tests/test_diaPipe.py
The DiaObject table is relatively small, so an additional check on the format is not too expensive.
=> DM-47274: Ensure that the DiaObject table has correct format after update

python/lsst/ap/association/ssSingleFrameAssociation.py
As we move single-frame association into prompt processing, we should match its connections to prompt processing rather than DRP, which it currently matches. calexp -> initial_pvi, src -> initial_stars_footprints_detector.
=> DM-47620 Match single frame association connections to prompt processing

data/DiaSource.yaml
...and add attempted dipole classification to APDB"
This reverts commit ecbbdbf337399f44f21a0f76abab90345d9bb79b.
=> DM-48009: Revert #248 "Rename dipole classification "flags” 

python/lsst/ap/association/diaPipe.py, tests/test_diaPipe.py, tests/test_metrics.py
This PR removes `DiaPipelineConfig.apdb` and updates `TotalUnassociatedDiaObjectsMetricTask` configs to account for lsst/verify#126.
=> DM-43419: Remove deprecated fields from DiaPipelineConfig

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/ssSingleFrameAssociation.py, python/lsst/ap/association/ssoAssociation.py, tests/test_diaPipe.py
Adds a new dataset, unAssocSsObjects, to the struct returned by ssoAssociation and sends it to the Butler as `ssSingleFrameUnassociatedObjects` through ssSingleFrameAssociation. Doesn't do anything to diaPipe, so this only affects SingleFrame.
=> DM-47648 : Return table of unassociated objects

tests/test_diaPipe.py
In-memory SQLite APDB does not really work since some time already.
=> DM-49464: Use on-disk APDB for tests

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/packageAlerts.py
This PR adds an extra `timeMethod` decorator (not useful for PP, but useful in general) and adds explicit, Loki-friendly logs for the things PP cares about.
I'm not sure why both methods use bespoke metadata formats instead of just using `timeMethod` or `time_this`, but I'm not going to try to clean that up here (it would probably break `analysis_tools`).
=> DM-49555: Expand diagnostic logs for Prompt Processing

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/packageAlerts.py
This PR changes the timing logs added in #272 from debug-level to verbose-level. That makes them easier to read in Prompt Processing without getting overwhelmed (in fact, we already log `lsst.diaPipe` at verbose level).
=> DM-49701: Make ap_association timing logs more visible to Prompt Processing

python/lsst/ap/association/diaPipe.py
Fixing a typo in the new dataset definitions before anyone uses the incorrect ones
=> DM-46495: Use parameters in new dataset types

python/lsst/ap/association/mpSkyEphemerisQuery.py
This PR adds a warning if the `MP_SKY_URL` is not defined and `mpSkyEphemerisQuery` needs to fall back to its default.
=> DM-50462: Add MPSky to Prompt Processing configs

python/lsst/ap/association/filterDiaSourceCatalog.py, tests/test_filterDiaSourceCatalog.py
The trailed source length is stored in units of pixels, but the threshold for filtering out long trailed sources is in arcseconds. Add a simple calculation to convert the trail length to the correct units before applying the filter.
=> DM-50570: Fix trailed source filter

python/lsst/ap/association/diaPipe.py, python/lsst/ap/association/loadDiaCatalogs.py, python/lsst/ap/association/packageAlerts.py
This PR modifies the `ap_association` timing code to run whether the timed operation succeeded or raised, then adds Loki-friendly logs to `LoadDiaCatalogsTask`.
=> DM-50035: Prompt Processing APDB download metric misses failed operations

data/DiaSource.yaml
This reverts commit 36860c3005f5ee111192f4cb9196888e3aa3e103, reversing changes made to b2c191e6fd8eca712aff58d3bf7c0260a7bd0e9d.
=> Revert DM-51228 - perform forced photometry on template
